# Generated by Django 5.0.3 on 2024-03-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='ifsc_code',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
